<#import "../common/common.ftlh" as common />

<@common.wrapping title="Приходная накладная | Автомойка">
    <h1>Автомойка</h1>

    <div class="list-group">
        <a href="/car-wash/car-wash-receiving-waybill" class="list-group-item list-group-item-action list-group-item-dark">Приходная накладная</a>
        <a href="/car-wash/car-wash-expensing-waybill" class="list-group-item list-group-item-action list-group-item-dark">Расходная накладная</a>
    </div>

</@common.wrapping>
