<#import "../common/common.ftlh" as common />

<@common.wrapping title="">

    <div class="list-group">
        <a href="/car-service/receiving-waybill" class="list-group-item list-group-item-action list-group-item-dark">Приходная накладная</a>
        <a href="/car-service/expensing-waybill" class="list-group-item list-group-item-action list-group-item-dark">Расходная накладная</a>
    </div>
</@common.wrapping>