<#import "../common/common.ftlh" as common />

<@common.wrapping title="Общие справочники">

    <@common.header>Общие справочники</@common.header>

    <div class="list-group">
        <a href="/common-catalogs/car-brands" class="list-group-item list-group-item-action list-group-item-dark">Автомобильные марки</a>
        <a href="/common-catalogs/detergents" class="list-group-item list-group-item-action list-group-item-dark">Моющие средства</a>
    </div>

</@common.wrapping>
