<#import "../common/common.ftlh" as common />

<@common.wrapping title="Главная | Автомобильный рынок">

        <@common.header>Автомобильный рынок</@common.header>

        <div class="list-group">
                <a href="/car-market/coming" class="list-group-item list-group-item-action list-group-item-dark">Приход</a>
                <a href="/car-market/sale" class="list-group-item list-group-item-action list-group-item-dark">Продажа</a>
        </div>

</@common.wrapping>